[workspace]
resolver = "2"
members = [
    "pg/calico",
    "pg/crawler",
    "pg/glimmer", 
    "pg/heimdall",
    "pg/porta",
    "pg/signal",
    "pg/vera", 
    "shared",
    "tools/vizzie",
    "util/dexter"
]