[package]
name = "acquisition"
version = "0.1.0"
edition = "2021"

[lib]
lib = "aqlib"
path = "src/lib.rs"

[[bin]]
name = "crawler"
path = "src/crawler.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8"
reqwest = "0.11"
robotstxt = "0.3"
scraper = "0.14"

[dev-dependencies]
mockito = "0.31"
