[package]
name = "acquisition"
version = "0.1.0"
edition = "2021"

[lib]
lib = "aqlib"
path = "src/lib.rs"

[[bin]]
name = "crawler"
path = "src/crawler.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"

[dev-dependencies]
mockito = "0.31"
