/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.nimbus

import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.streaming.OutputMode

object App {
  def main(args: Array[String]): Unit = {
     val sparkSession = SparkSession.builder.
          master("local[2]")
          .appName("streaming example")
          .getOrCreate()


    val dataSource = "com.calico.spark.sources.calico"

    val batchDf = sparkSession
      .read
      .format(dataSource)
      .load()

    batchDf.show()

    /**
    val streamingDf = sparkSession.
      readStream.
      format(dataSource)
      .load()

    val query = streamingDf.writeStream
      .format("console")
      .queryName("simple_source")
    .outputMode(OutputMode.Append())

    query.start().awaitTermination()
    */
 }

  def greeting(): String = "Hello, world!"
}
